export const shoesCollection = [
    {
      id: 1,
      name: "Nike Air Monarch IV",
      brand: "Nike",
      category: "Sneakers",
      description: "Comfortable running sneaker",
      price: 120,
      rating: 4.5,
      color: "White",
      stock: 34,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    },
    {
      id: 2,
      name: "Nike Air VaporMax Plus",
      brand: "Nike",
      category: "Running",
      description: "Premium running shoe",
      price: 180,
      rating: 4.7,
      color: "Red",
      stock: 20,
      image: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb",
    },
    {
      id: 3,
      name: "Adidas Ultraboost",
      brand: "Adidas",
      category: "Running",
      description: "Responsive cushioning shoe",
      price: 160,
      rating: 4.8,
      color: "Black",
      stock: 18,
      image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f",
    },
    {
      id: 4,
      name: "Puma RS-X",
      brand: "Puma",
      category: "Sneakers",
      description: "Retro style sneaker",
      price: 110,
      rating: 4.3,
      color: "Blue",
      stock: 26,
      image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5",
    },
    {
      id: 5,
      name: "Vans Old Skool",
      brand: "Vans",
      category: "Casual",
      description: "Classic skate shoe",
      price: 90,
      rating: 4.4,
      color: "Black",
      stock: 40,
      image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77",
    },
    {
      id: 6,
      name: "Reebok Zig Kinetica",
      brand: "Reebok",
      category: "Sports",
      description: "High performance sports shoe",
      price: 140,
      rating: 4.2,
      color: "Grey",
      stock: 25,
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 7,
      name: "Converse Chuck Taylor",
      brand: "Converse",
      category: "Casual",
      description: "Iconic everyday sneaker",
      price: 70,
      rating: 4.6,
      color: "White",
      stock: 50,
      image: "https://images.unsplash.com/photo-1514989940723-e8e51635b782",
    },
    {
      id: 8,
      name: "New Balance 574",
      brand: "New Balance",
      category: "Sneakers",
      description: "Classic lifestyle sneaker",
      price: 100,
      rating: 4.5,
      color: "Grey",
      stock: 28,
      image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2",
    },
    {
      id: 9,
      name: "ASICS Gel Kayano",
      brand: "ASICS",
      category: "Running",
      description: "Stability running shoe",
      price: 170,
      rating: 4.7,
      color: "Blue",
      stock: 16,
      image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5",
    },
    {
      id: 10,
      name: "Fila Disruptor II",
      brand: "Fila",
      category: "Sneakers",
      description: "Chunky fashion sneaker",
      price: 95,
      rating: 4.1,
      color: "White",
      stock: 22,
      image: "https://images.unsplash.com/photo-1549298916-b41d501d3772",
    },
  
    {
      id: 11,
      name: "Nike Revolution 6",
      brand: "Nike",
      category: "Running",
      description: "Lightweight training shoe",
      price: 85,
      rating: 4.4,
      color: "Black",
      stock: 30,
      image: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb",
    },
    {
      id: 12,
      name: "Adidas Samba",
      brand: "Adidas",
      category: "Casual",
      description: "Streetwear classic sneaker",
      price: 99,
      rating: 4.7,
      color: "White",
      stock: 35,
      image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f",
    },
    {
      id: 13,
      name: "Puma Velocity Nitro",
      brand: "Puma",
      category: "Running",
      description: "Responsive running shoe",
      price: 130,
      rating: 4.5,
      color: "Green",
      stock: 18,
      image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5",
    },
    {
      id: 14,
      name: "Under Armour HOVR",
      brand: "Under Armour",
      category: "Sports",
      description: "Comfort-focused athletic shoe",
      price: 145,
      rating: 4.3,
      color: "Black",
      stock: 24,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    },
    {
      id: 15,
      name: "Skechers Go Walk",
      brand: "Skechers",
      category: "Walking",
      description: "Soft comfortable walking shoe",
      price: 75,
      rating: 4.6,
      color: "Navy",
      stock: 44,
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 16,
      name: "Nike Pegasus Trail",
      brand: "Nike",
      category: "Running",
      description: "Durable trail running shoe",
      price: 155,
      rating: 4.6,
      color: "Orange",
      stock: 19,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    },
    {
      id: 17,
      name: "Adidas NMD R1",
      brand: "Adidas",
      category: "Sneakers",
      description: "Urban lifestyle sneaker",
      price: 140,
      rating: 4.7,
      color: "Black",
      stock: 27,
      image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f",
    },
    {
      id: 18,
      name: "Puma Future Rider",
      brand: "Puma",
      category: "Casual",
      description: "Retro inspired casual shoe",
      price: 95,
      rating: 4.3,
      color: "Yellow",
      stock: 31,
      image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5",
    },
    {
      id: 19,
      name: "Reebok Nano X",
      brand: "Reebok",
      category: "Sports",
      description: "Cross training performance shoe",
      price: 135,
      rating: 4.5,
      color: "Grey",
      stock: 22,
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 20,
      name: "Vans Era",
      brand: "Vans",
      category: "Casual",
      description: "Classic low top skate shoe",
      price: 80,
      rating: 4.4,
      color: "White",
      stock: 45,
      image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77",
    },
    {
      id: 21,
      name: "ASICS Gel Nimbus",
      brand: "ASICS",
      category: "Running",
      description: "Long distance running comfort",
      price: 175,
      rating: 4.8,
      color: "Blue",
      stock: 17,
      image: "https://images.unsplash.com/photo-1549298916-b41d501d3772",
    },
    {
      id: 22,
      name: "Fila Ray Tracer",
      brand: "Fila",
      category: "Sneakers",
      description: "Chunky retro sneaker",
      price: 92,
      rating: 4.1,
      color: "Red",
      stock: 29,
      image: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb",
    },
    {
      id: 23,
      name: "Converse Run Star Hike",
      brand: "Converse",
      category: "Sneakers",
      description: "Platform sneaker with bold design",
      price: 115,
      rating: 4.6,
      color: "Black",
      stock: 20,
      image: "https://images.unsplash.com/photo-1514989940723-e8e51635b782",
    },
    {
      id: 24,
      name: "New Balance Fresh Foam",
      brand: "New Balance",
      category: "Running",
      description: "Soft cushioned running shoe",
      price: 145,
      rating: 4.7,
      color: "Grey",
      stock: 26,
      image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2",
    },
    {
      id: 25,
      name: "Under Armour Charged Rogue",
      brand: "Under Armour",
      category: "Sports",
      description: "Versatile gym training shoe",
      price: 125,
      rating: 4.4,
      color: "Black",
      stock: 23,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    },
    {
      id: 26,
      name: "Skechers Max Cushioning",
      brand: "Skechers",
      category: "Walking",
      description: "Ultra comfort walking shoe",
      price: 88,
      rating: 4.5,
      color: "Navy",
      stock: 38,
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 27,
      name: "Nike Blazer Mid",
      brand: "Nike",
      category: "Sneakers",
      description: "Vintage basketball inspired sneaker",
      price: 110,
      rating: 4.6,
      color: "White",
      stock: 24,
      image: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb",
    },
    {
      id: 28,
      name: "Adidas Forum Low",
      brand: "Adidas",
      category: "Sneakers",
      description: "Classic basketball street sneaker",
      price: 120,
      rating: 4.5,
      color: "Blue",
      stock: 21,
      image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f",
    },
    {
      id: 29,
      name: "Puma Suede Classic",
      brand: "Puma",
      category: "Casual",
      description: "Iconic suede streetwear shoe",
      price: 85,
      rating: 4.4,
      color: "Green",
      stock: 33,
      image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5",
    },
    {
      id: 30,
      name: "Reebok Club C 85",
      brand: "Reebok",
      category: "Casual",
      description: "Minimal clean tennis sneaker",
      price: 90,
      rating: 4.5,
      color: "White",
      stock: 36,
      image: "https://images.unsplash.com/photo-1549298916-b41d501d3772",
    },
    {
      id: 31,
      name: "Nike Zoom Fly",
      brand: "Nike",
      category: "Running",
      description: "Lightweight marathon running shoe",
      price: 165,
      rating: 4.8,
      color: "Black",
      stock: 18,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    },
    {
      id: 32,
      name: "Adidas Superstar",
      brand: "Adidas",
      category: "Sneakers",
      description: "Classic shell toe sneaker",
      price: 100,
      rating: 4.7,
      color: "White",
      stock: 40,
      image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f",
    },
    {
      id: 33,
      name: "Puma Ignite Flash",
      brand: "Puma",
      category: "Sports",
      description: "High energy training shoe",
      price: 118,
      rating: 4.4,
      color: "Red",
      stock: 25,
      image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5",
    },
    {
      id: 34,
      name: "Reebok Floatride Energy",
      brand: "Reebok",
      category: "Running",
      description: "Responsive running sneaker",
      price: 130,
      rating: 4.5,
      color: "Blue",
      stock: 21,
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 35,
      name: "Vans Slip-On",
      brand: "Vans",
      category: "Casual",
      description: "Easy wear slip-on shoe",
      price: 75,
      rating: 4.6,
      color: "Black",
      stock: 48,
      image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77",
    },
    {
      id: 36,
      name: "ASICS GT 2000",
      brand: "ASICS",
      category: "Running",
      description: "Stability focused running shoe",
      price: 155,
      rating: 4.7,
      color: "Grey",
      stock: 19,
      image: "https://images.unsplash.com/photo-1549298916-b41d501d3772",
    },
    {
      id: 37,
      name: "Fila Memory Workshift",
      brand: "Fila",
      category: "Walking",
      description: "Comfortable work and walking shoe",
      price: 82,
      rating: 4.2,
      color: "Black",
      stock: 32,
      image: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb",
    },
    {
      id: 38,
      name: "Converse One Star",
      brand: "Converse",
      category: "Sneakers",
      description: "Low top suede sneaker",
      price: 95,
      rating: 4.5,
      color: "Green",
      stock: 28,
      image: "https://images.unsplash.com/photo-1514989940723-e8e51635b782",
    },
    {
      id: 39,
      name: "New Balance 997H",
      brand: "New Balance",
      category: "Casual",
      description: "Everyday lifestyle sneaker",
      price: 105,
      rating: 4.4,
      color: "Navy",
      stock: 30,
      image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2",
    },
    {
      id: 40,
      name: "Under Armour Curry Flow",
      brand: "Under Armour",
      category: "Sports",
      description: "Basketball performance shoe",
      price: 170,
      rating: 4.8,
      color: "White",
      stock: 14,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    },
    {
      id: 41,
      name: "Skechers Arch Fit",
      brand: "Skechers",
      category: "Walking",
      description: "Arch support comfort shoe",
      price: 92,
      rating: 4.6,
      color: "Grey",
      stock: 41,
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 42,
      name: "Nike Dunk Low",
      brand: "Nike",
      category: "Sneakers",
      description: "Popular low top sneaker",
      price: 125,
      rating: 4.9,
      color: "Blue",
      stock: 26,
      image: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb",
    },
    {
      id: 43,
      name: "Adidas Gazelle",
      brand: "Adidas",
      category: "Casual",
      description: "Timeless suede sneaker",
      price: 98,
      rating: 4.5,
      color: "Red",
      stock: 34,
      image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f",
    },
    {
      id: 44,
      name: "Puma Deviate Nitro",
      brand: "Puma",
      category: "Running",
      description: "Elite speed running shoe",
      price: 185,
      rating: 4.7,
      color: "Orange",
      stock: 13,
      image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5",
    },
    {
      id: 45,
      name: "Reebok Classic Leather",
      brand: "Reebok",
      category: "Sneakers",
      description: "Classic leather lifestyle shoe",
      price: 89,
      rating: 4.4,
      color: "White",
      stock: 39,
      image: "https://images.unsplash.com/photo-1549298916-b41d501d3772",
    },
    {
      id: 46,
      name: "Nike Free Run 5.0",
      brand: "Nike",
      category: "Running",
      description: "Flexible lightweight running shoe",
      price: 115,
      rating: 4.5,
      color: "Grey",
      stock: 27,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    },
    {
      id: 47,
      name: "Adidas Terrex Swift",
      brand: "Adidas",
      category: "Sports",
      description: "Outdoor hiking performance shoe",
      price: 145,
      rating: 4.6,
      color: "Green",
      stock: 18,
      image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f",
    },
    {
      id: 48,
      name: "Puma Cali Star",
      brand: "Puma",
      category: "Sneakers",
      description: "Modern streetwear sneaker",
      price: 105,
      rating: 4.4,
      color: "White",
      stock: 29,
      image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5",
    },
    {
      id: 49,
      name: "Reebok Nano Flex",
      brand: "Reebok",
      category: "Sports",
      description: "Training shoe with flexible support",
      price: 128,
      rating: 4.3,
      color: "Black",
      stock: 22,
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 50,
      name: "Vans Sk8 Hi",
      brand: "Vans",
      category: "Casual",
      description: "High top skate inspired sneaker",
      price: 92,
      rating: 4.7,
      color: "Black",
      stock: 35,
      image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77",
    },
    {
      id: 51,
      name: "ASICS Gel Lyte III",
      brand: "ASICS",
      category: "Sneakers",
      description: "Retro running inspired sneaker",
      price: 138,
      rating: 4.5,
      color: "Blue",
      stock: 24,
      image: "https://images.unsplash.com/photo-1549298916-b41d501d3772",
    },
    {
      id: 52,
      name: "Fila Oakmont TR",
      brand: "Fila",
      category: "Sports",
      description: "Trail inspired rugged sneaker",
      price: 98,
      rating: 4.1,
      color: "Brown",
      stock: 31,
      image: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb",
    },
    {
      id: 53,
      name: "Converse Lift Platform",
      brand: "Converse",
      category: "Sneakers",
      description: "Platform style casual sneaker",
      price: 108,
      rating: 4.6,
      color: "Pink",
      stock: 26,
      image: "https://images.unsplash.com/photo-1514989940723-e8e51635b782",
    },
    {
      id: 54,
      name: "New Balance FuelCell",
      brand: "New Balance",
      category: "Running",
      description: "Speed focused running shoe",
      price: 172,
      rating: 4.8,
      color: "Orange",
      stock: 16,
      image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2",
    },
    {
      id: 55,
      name: "Under Armour Spawn",
      brand: "Under Armour",
      category: "Sports",
      description: "Basketball performance sneaker",
      price: 160,
      rating: 4.7,
      color: "Red",
      stock: 15,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    },
    {
      id: 56,
      name: "Skechers D'Lites",
      brand: "Skechers",
      category: "Casual",
      description: "Chunky retro comfort shoe",
      price: 86,
      rating: 4.4,
      color: "White",
      stock: 38,
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 57,
      name: "Nike Court Vision",
      brand: "Nike",
      category: "Sneakers",
      description: "Basketball inspired lifestyle shoe",
      price: 112,
      rating: 4.5,
      color: "White",
      stock: 33,
      image: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb",
    },
    {
      id: 58,
      name: "Adidas ZX 2K Boost",
      brand: "Adidas",
      category: "Running",
      description: "Boost cushioning comfort sneaker",
      price: 150,
      rating: 4.6,
      color: "Grey",
      stock: 20,
      image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f",
    },
    {
      id: 59,
      name: "Puma Mirage Sport",
      brand: "Puma",
      category: "Sneakers",
      description: "Bold futuristic sneaker design",
      price: 118,
      rating: 4.3,
      color: "Purple",
      stock: 23,
      image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5",
    },
    {
      id: 60,
      name: "Reebok Royal Glide",
      brand: "Reebok",
      category: "Casual",
      description: "Simple everyday comfort sneaker",
      price: 84,
      rating: 4.2,
      color: "Navy",
      stock: 37,
      image: "https://images.unsplash.com/photo-1549298916-b41d501d3772",
    },
    {
      id: 61,
      name: "Nike Metcon 8",
      brand: "Nike",
      category: "Sports",
      description: "Training shoe for gym workouts",
      price: 142,
      rating: 4.7,
      color: "Black",
      stock: 21,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    },
    {
      id: 62,
      name: "Adidas Stan Smith",
      brand: "Adidas",
      category: "Casual",
      description: "Minimal timeless tennis sneaker",
      price: 95,
      rating: 4.8,
      color: "White",
      stock: 42,
      image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f",
    },
    {
      id: 63,
      name: "Puma Flyer Runner",
      brand: "Puma",
      category: "Running",
      description: "Affordable lightweight running shoe",
      price: 89,
      rating: 4.2,
      color: "Blue",
      stock: 30,
      image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5",
    },
    {
      id: 64,
      name: "Reebok Pump Omni Zone",
      brand: "Reebok",
      category: "Sneakers",
      description: "Retro basketball sneaker",
      price: 155,
      rating: 4.5,
      color: "White",
      stock: 17,
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 65,
      name: "Vans Authentic",
      brand: "Vans",
      category: "Casual",
      description: "Classic canvas skate shoe",
      price: 72,
      rating: 4.6,
      color: "Red",
      stock: 46,
      image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77",
    },
    {
      id: 66,
      name: "ASICS Novablast",
      brand: "ASICS",
      category: "Running",
      description: "High bounce running sneaker",
      price: 168,
      rating: 4.8,
      color: "Orange",
      stock: 15,
      image: "https://images.unsplash.com/photo-1549298916-b41d501d3772",
    },
    {
      id: 67,
      name: "Fila Renno",
      brand: "Fila",
      category: "Sneakers",
      description: "Retro inspired chunky sneaker",
      price: 94,
      rating: 4.1,
      color: "Yellow",
      stock: 28,
      image: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb",
    },
    {
      id: 68,
      name: "Converse Weapon CX",
      brand: "Converse",
      category: "Sports",
      description: "Basketball sneaker with CX foam",
      price: 132,
      rating: 4.4,
      color: "Purple",
      stock: 20,
      image: "https://images.unsplash.com/photo-1514989940723-e8e51635b782",
    },
    {
      id: 69,
      name: "New Balance 327",
      brand: "New Balance",
      category: "Sneakers",
      description: "Vintage runner inspired sneaker",
      price: 118,
      rating: 4.7,
      color: "Green",
      stock: 26,
      image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2",
    },
    {
      id: 70,
      name: "Under Armour Lockdown",
      brand: "Under Armour",
      category: "Sports",
      description: "Basketball shoe with ankle support",
      price: 138,
      rating: 4.3,
      color: "Black",
      stock: 18,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    },
    {
      id: 71,
      name: "Skechers Flex Advantage",
      brand: "Skechers",
      category: "Walking",
      description: "Flexible all day comfort shoe",
      price: 79,
      rating: 4.5,
      color: "Grey",
      stock: 40,
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 72,
      name: "Nike Air Force 1",
      brand: "Nike",
      category: "Sneakers",
      description: "Iconic streetwear sneaker",
      price: 125,
      rating: 4.9,
      color: "White",
      stock: 34,
      image: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb",
    },
    {
      id: 73,
      name: "Adidas Response Super",
      brand: "Adidas",
      category: "Running",
      description: "Comfort daily running shoe",
      price: 128,
      rating: 4.4,
      color: "Blue",
      stock: 24,
      image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f",
    },
    {
      id: 74,
      name: "Puma Axelion",
      brand: "Puma",
      category: "Sports",
      description: "Bold athletic training shoe",
      price: 110,
      rating: 4.3,
      color: "Red",
      stock: 29,
      image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5",
    },
    {
      id: 75,
      name: "Reebok Zig Dynamica",
      brand: "Reebok",
      category: "Running",
      description: "Energy return running shoe",
      price: 122,
      rating: 4.4,
      color: "Navy",
      stock: 22,
      image: "https://images.unsplash.com/photo-1549298916-b41d501d3772",
    },
    {
      id: 76,
      name: "Nike React Infinity Run",
      brand: "Nike",
      category: "Running",
      description: "Smooth cushioned running shoe",
      price: 175,
      rating: 4.8,
      color: "Blue",
      stock: 18,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    },
    {
      id: 77,
      name: "Adidas AlphaBoost",
      brand: "Adidas",
      category: "Sports",
      description: "Responsive boost training sneaker",
      price: 135,
      rating: 4.5,
      color: "Black",
      stock: 23,
      image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f",
    },
    {
      id: 78,
      name: "Puma Wild Rider",
      brand: "Puma",
      category: "Sneakers",
      description: "Retro futuristic casual sneaker",
      price: 115,
      rating: 4.4,
      color: "Purple",
      stock: 27,
      image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5",
    },
    {
      id: 79,
      name: "Reebok Energen Plus",
      brand: "Reebok",
      category: "Running",
      description: "Daily running comfort shoe",
      price: 118,
      rating: 4.3,
      color: "Grey",
      stock: 30,
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 80,
      name: "Vans UltraRange EXO",
      brand: "Vans",
      category: "Casual",
      description: "Adventure ready lightweight sneaker",
      price: 108,
      rating: 4.6,
      color: "Green",
      stock: 25,
      image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77",
    },
    {
      id: 81,
      name: "ASICS Gel Quantum",
      brand: "ASICS",
      category: "Sports",
      description: "High impact cushioning sneaker",
      price: 162,
      rating: 4.7,
      color: "White",
      stock: 19,
      image: "https://images.unsplash.com/photo-1549298916-b41d501d3772",
    },
    {
      id: 82,
      name: "Fila Electrove",
      brand: "Fila",
      category: "Sneakers",
      description: "Stylish streetwear sneaker",
      price: 96,
      rating: 4.2,
      color: "Blue",
      stock: 33,
      image: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb",
    },
    {
      id: 83,
      name: "Converse CX Explore",
      brand: "Converse",
      category: "Casual",
      description: "Modern comfort high top shoe",
      price: 120,
      rating: 4.5,
      color: "Orange",
      stock: 22,
      image: "https://images.unsplash.com/photo-1514989940723-e8e51635b782",
    },
    {
      id: 84,
      name: "New Balance 550",
      brand: "New Balance",
      category: "Sneakers",
      description: "Basketball inspired retro sneaker",
      price: 130,
      rating: 4.8,
      color: "White",
      stock: 24,
      image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2",
    },
    {
      id: 85,
      name: "Under Armour HOVR Sonic",
      brand: "Under Armour",
      category: "Running",
      description: "Energy return running shoe",
      price: 148,
      rating: 4.4,
      color: "Red",
      stock: 21,
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    },
    {
      id: 86,
      name: "Skechers Go Run Elevate",
      brand: "Skechers",
      category: "Running",
      description: "Lightweight responsive runner",
      price: 88,
      rating: 4.5,
      color: "Black",
      stock: 36,
      image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
    },
    {
      id: 87,
      name: "Nike Zoom Freak",
      brand: "Nike",
      category: "Sports",
      description: "Basketball shoe with grip support",
      price: 158,
      rating: 4.7,
      color: "Green",
      stock: 17,
      image: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb",
    },
    {
      id: 88,
      name: "Adidas Crazychaos",
      brand: "Adidas",
      category: "Sneakers",
      description: "Chunky everyday lifestyle sneaker",
      price: 104,
      rating: 4.3,
      color: "Grey",
      stock: 31,
      image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f",
    },
    {
      id: 89,
      name: "Puma Tazon 6",
      brand: "Puma",
      category: "Sports",
      description: "Training shoe with stable fit",
      price: 99,
      rating: 4.2,
      color: "Black",
      stock: 34,
      image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5",
    },
    {
      id: 90,
      name: "Reebok Lite Plus",
      brand: "Reebok",
      category: "Walking",
      description: "Comfortable lightweight walking shoe",
      price: 82,
      rating: 4.4,
      color: "White",
      stock: 40,
      image: "https://images.unsplash.com/photo-1549298916-b41d501d3772",
    },
  ];
  